### ISSUE TITLE
Slack Fingerprint

### ISSUE THREAD

**Issue by andystumpf** [witnessmenow/arduino-slack-api#3]
Can we please test if the fingerprint is still valid?   I've tested my Slack API https://api.slack.com/methods/api.test and the test works. After following your great vide https://www.youtube.com/watch?v=FBLbe8K9veg&t=431s but serial monitor is printing 
20:42:41.156 -> 13 is connected
20:42:42.074 -> {"profile": { "status_text": "I am the first status","status_emoji": ":sparkling_heart:","status_expiration": 0}}
20:42:42.366 -> Connection failed
20:42:42.366 -> error getting profile

**Comment by gilbertfrancois** [comment]
The certificate has been expired on the first of February. The fingerprint needs to be updated. 

Verstuurd vanaf mijn iPhone

**Comment by andystumpf** [comment]
Editing to 
`#define SLACK_FINGERPRINT "71 F8 C3 80 FE 88 B8 AB 30 8B 3F E1 5E B8 F6 76 98 78 CC 30"`
