### ISSUE TITLE
Getting Errors when using the examples

### ISSUE THREAD

**Issue by cbittne** [witnessmenow/arduino-slack-api#4]
When running the example code for the ESP8266, I am getting the following error:

WiFi connected
IP address: 
192.168.1.141
{"profile": { "status_text": "I am the first status","status_emoji": ":sparkling_heart:","status_expiration": 0}}
Connection failed
error getting profile

Not sure if this means the fingerprint has changed or if Slack has change anything on their end.  I have validated that internet access is working and the the Slack Access Token is working

**Comment by mrFramstad** [comment]
I got this working by examining Slacks SSL cert and changing the following in ArduinoSlack.h:

// Fingerprint correct as of March 11th 2021
#define SLACK_FINGERPRINT "71 F8 C3 80 FE 88 B8 AB 30 8B 3F E1 5E B8 F6 76 98 78 CC 30"

**Comment by cbittne** [comment]
Confirmed, updating the SLACK_FINGERPRINT does fix the issue.

Thanks
